spring:
  datasource:
    url: jdbc:mysql://db.fengdai.org:3306/ucenter_1.2.0?characterEncoding=utf8&defaultCharacterSet=utf8&allowMultiQueries=true&autoReconnect=true
    username: csp
    password: csp2017DEV9
    druid:
      initial-size: 8
      min-idle: 8
      max-active: 32
      test-on-borrow: false
      test-while-idle: true
      validation-query: SELECT 1
      min-evictable-idle-time-millis: 30000
      time-between-eviction-runs-millis: 10000
      keep-alive: true
      db-type: mysql
      poolPreparedStatements: false
      maxOpenPreparedStatements: -1
      driver-class-name: com.mysql.jdbc.Driver
      filter:
        stat:
          enabled: true
      stat-view-servlet:
        enabled: true